
import os
import socket
import subprocess
import sys
from pathlib import Path

def is_port_in_use(port: int) -> bool:
    """Check if a port is currently in use."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('localhost', port)) == 0

def find_available_port(start_port: int, max_retries: int = 10) -> int:
    """Find the first available port starting from start_port."""
    for port in range(start_port, start_port + max_retries):
        if not is_port_in_use(port):
            return port
    return -1

def update_frontend_config(backend_port: int):
    """Update frontend environment variables with the new backend port."""
    frontend_dir = Path(__file__).parent.parent / "frontend"
    env_file = frontend_dir / ".env.local"
    
    print(f"Updating frontend config at {env_file}...")
    
    config_content = f"""# Auto-generated by backend/run.py
NEXT_PUBLIC_API_URL=http://localhost:{backend_port}
INTERNAL_API_URL=http://localhost:{backend_port}
"""
    
    try:
        with open(env_file, 'w') as f:
            f.write(config_content)
        print(f"✅ Frontend configured to use backend on port {backend_port}")
    except Exception as e:
        print(f"❌ Failed to update frontend config: {e}")

def main():
    print("AI Engineering Study Assistant - Backend Launcher")
    print("===============================================")
    
    # 1. Find a port
    start_port = 8000
    port = find_available_port(start_port)
    
    if port == -1:
        print(f"❌ Could not find an available port between {start_port} and {start_port + 10}")
        sys.exit(1)
        
    print(f"✅ Found available port: {port}")
    
    # 2. Update Frontend
    update_frontend_config(port)
    
    # 3. Set Environment Variables
    # Ensure DB URL is set (workaround for .env issues)
    # NOTE: Don't force localhost in environments where Postgres is in Docker.
    if "DATABASE_URL" not in os.environ:
        in_docker = os.path.exists("/.dockerenv") or os.getenv("DOCKER") == "true"
        default_db = (
            "postgresql://postgres:postgres@db:5432/engineering_os"
            if in_docker
            else "postgresql://postgres:postgres@localhost:5432/engineering_os"
        )
        os.environ["DATABASE_URL"] = default_db
        print(f"✅ Injected DATABASE_URL = {default_db}")
        
    # 4. Start Uvicorn
    print(f"\n🚀 Starting backend on http://localhost:{port}...")
    try:
        # Use sys.executable to ensure we use the same python interpreter
        cmd = [
            sys.executable, "-m", "uvicorn", "main:app", 
            "--reload", 
            "--port", str(port),
            "--host", "127.0.0.1" 
        ]
        
        # Run process
        subprocess.run(cmd, env=os.environ.copy())
        
    except KeyboardInterrupt:
        print("\nStopping server...")
    except Exception as e:
        print(f"\n❌ Error starting server: {e}")

if __name__ == "__main__":
    main()
